EPICS_PV:
  IN_BEAM_X: EXP:JEDI:JEPO:InBeamPos:X
  GET_BEAM_X: EXP:JEDI:JEPO:GetPos:X
  DELTA_X: EXP:JEDI:JEPO:DeltaPos:X
  HOME_X: EXP:JEDI:JEPO:HOME:X
  STATUS_X: EXP:JEDI:JEPO:Status:X
  IN_BEAM_Y: EXP:JEDI:JEPO:InBeamPos:Y
  GET_BEAM_Y: EXP:JEDI:JEPO:GetPos:Y
  DELTA_Y: EXP:JEDI:JEPO:DeltaPos:Y
  HOME_Y: EXP:JEDI:JEPO:HOME:Y
  STATUS_Y: EXP:JEDI:JEPO:Status:Y
  MODE: EXP:JEDI:JEPO:MODE
  GUI: EXP:JEDI:JEPO:GUI
  COMMAND: EXP:JEDI:JEPO:COMMAND
  
VERT_INBEAM_DEFOULT_VALUE: 200
HOR_INBEAM_DEFOULT_VALUE: 200

VERT_DELTA_DEFOULT_VALUE: 25
HOR_DELTA_DEFOULT_VALUE: 25

VERT_HOME_DEFOULT_VALUE: 1000
HOR_HOME_DEFOULT_VALUE: 1000
