# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JEPO_TARGET_CONTROL.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 780))
        MainWindow.setMouseTracking(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.on_off_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.on_off_BTN.setGeometry(QtCore.QRect(30, 30, 120, 48))
        self.on_off_BTN.setAutoDefault(False)
        self.on_off_BTN.setDefault(False)
        self.on_off_BTN.setFlat(False)
        self.on_off_BTN.setObjectName("on_off_BTN")
        self.GROUP_VERTICAL = QtWidgets.QGroupBox(self.centralwidget)
        self.GROUP_VERTICAL.setEnabled(True)
        self.GROUP_VERTICAL.setGeometry(QtCore.QRect(30, 130, 485, 331))
        self.GROUP_VERTICAL.setAutoFillBackground(False)
        self.GROUP_VERTICAL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.GROUP_VERTICAL.setFlat(True)
        self.GROUP_VERTICAL.setCheckable(False)
        self.GROUP_VERTICAL.setObjectName("GROUP_VERTICAL")
        self.VERTICAL_HOME_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_SET_BUTTON.setEnabled(True)
        self.VERTICAL_HOME_SET_BUTTON.setGeometry(QtCore.QRect(250, 235, 60, 60))
        self.VERTICAL_HOME_SET_BUTTON.setObjectName("VERTICAL_HOME_SET_BUTTON")
        self.VERTICAL_DELTA_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_SET_BUTTON.setEnabled(True)
        self.VERTICAL_DELTA_SET_BUTTON.setGeometry(QtCore.QRect(250, 155, 60, 60))
        self.VERTICAL_DELTA_SET_BUTTON.setObjectName("VERTICAL_DELTA_SET_BUTTON")
        self.VERTICAL_IN_BEAM_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_SET_BUTTON.setEnabled(True)
        self.VERTICAL_IN_BEAM_SET_BUTTON.setGeometry(QtCore.QRect(249, 75, 60, 60))
        self.VERTICAL_IN_BEAM_SET_BUTTON.setObjectName("VERTICAL_IN_BEAM_SET_BUTTON")
        self.VERTICAL_IN_BEAM_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_TEXT_IN.setEnabled(True)
        self.VERTICAL_IN_BEAM_TEXT_IN.setGeometry(QtCore.QRect(110, 75, 120, 60))
        self.VERTICAL_IN_BEAM_TEXT_IN.setAccessibleName("")
        self.VERTICAL_IN_BEAM_TEXT_IN.setAutoFillBackground(False)
        self.VERTICAL_IN_BEAM_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_IN_BEAM_TEXT_IN.setInputMask("")
        self.VERTICAL_IN_BEAM_TEXT_IN.setText("")
        self.VERTICAL_IN_BEAM_TEXT_IN.setFrame(True)
        self.VERTICAL_IN_BEAM_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_IN_BEAM_TEXT_IN.setPlaceholderText("")
        self.VERTICAL_IN_BEAM_TEXT_IN.setClearButtonEnabled(False)
        self.VERTICAL_IN_BEAM_TEXT_IN.setObjectName("VERTICAL_IN_BEAM_TEXT_IN")
        self.VERTICAL_DELTA_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_TEXT_IN.setEnabled(True)
        self.VERTICAL_DELTA_TEXT_IN.setGeometry(QtCore.QRect(110, 155, 120, 60))
        self.VERTICAL_DELTA_TEXT_IN.setAccessibleName("")
        self.VERTICAL_DELTA_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_DELTA_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_DELTA_TEXT_IN.setObjectName("VERTICAL_DELTA_TEXT_IN")
        self.VERTICAL_HOME_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_TEXT_IN.setEnabled(True)
        self.VERTICAL_HOME_TEXT_IN.setGeometry(QtCore.QRect(110, 235, 120, 60))
        self.VERTICAL_HOME_TEXT_IN.setAccessibleName("")
        self.VERTICAL_HOME_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.VERTICAL_HOME_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.VERTICAL_HOME_TEXT_IN.setObjectName("VERTICAL_HOME_TEXT_IN")
        self.IN_BEAM_TEXT = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.IN_BEAM_TEXT.setEnabled(True)
        self.IN_BEAM_TEXT.setGeometry(QtCore.QRect(20, 85, 129, 34))
        self.IN_BEAM_TEXT.setObjectName("IN_BEAM_TEXT")
        self.DELTA_POS = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.DELTA_POS.setEnabled(True)
        self.DELTA_POS.setGeometry(QtCore.QRect(20, 165, 151, 34))
        self.DELTA_POS.setObjectName("DELTA_POS")
        self.HOME_TEXT = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.HOME_TEXT.setEnabled(True)
        self.HOME_TEXT.setGeometry(QtCore.QRect(20, 248, 129, 34))
        self.HOME_TEXT.setObjectName("HOME_TEXT")
        self.MOVE_Y_INBEAM = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_INBEAM.setGeometry(QtCore.QRect(330, 75, 141, 60))
        self.MOVE_Y_INBEAM.setObjectName("MOVE_Y_INBEAM")
        self.MOVE_Y_OUTBEAM = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_OUTBEAM.setGeometry(QtCore.QRect(330, 155, 141, 60))
        self.MOVE_Y_OUTBEAM.setObjectName("MOVE_Y_OUTBEAM")
        self.MOVE_Y_HOME = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.MOVE_Y_HOME.setGeometry(QtCore.QRect(330, 235, 141, 60))
        self.MOVE_Y_HOME.setObjectName("MOVE_Y_HOME")
        self.auto_manual_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_manual_checkbox.setGeometry(QtCore.QRect(170, 33, 175, 40))
        self.auto_manual_checkbox.setObjectName("auto_manual_checkbox")
        self.GROUP_HORISONTAL = QtWidgets.QGroupBox(self.centralwidget)
        self.GROUP_HORISONTAL.setEnabled(True)
        self.GROUP_HORISONTAL.setGeometry(QtCore.QRect(590, 130, 485, 331))
        self.GROUP_HORISONTAL.setAutoFillBackground(False)
        self.GROUP_HORISONTAL.setFlat(True)
        self.GROUP_HORISONTAL.setCheckable(False)
        self.GROUP_HORISONTAL.setObjectName("GROUP_HORISONTAL")
        self.HORISONTAL_HOME_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_HOME_SET_BUTTON.setEnabled(True)
        self.HORISONTAL_HOME_SET_BUTTON.setGeometry(QtCore.QRect(250, 235, 60, 60))
        self.HORISONTAL_HOME_SET_BUTTON.setObjectName("HORISONTAL_HOME_SET_BUTTON")
        self.HORISONTAL_DELTA_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_DELTA_SET_BUTTON.setEnabled(True)
        self.HORISONTAL_DELTA_SET_BUTTON.setGeometry(QtCore.QRect(250, 155, 60, 60))
        self.HORISONTAL_DELTA_SET_BUTTON.setObjectName("HORISONTAL_DELTA_SET_BUTTON")
        self.HORISONTAL_IN_BEAM_SET_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_IN_BEAM_SET_BUTTON.setEnabled(True)
        self.HORISONTAL_IN_BEAM_SET_BUTTON.setGeometry(QtCore.QRect(249, 75, 60, 60))
        self.HORISONTAL_IN_BEAM_SET_BUTTON.setObjectName("HORISONTAL_IN_BEAM_SET_BUTTON")
        self.HORISONTAL_IN_BEAM_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setEnabled(True)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setGeometry(QtCore.QRect(110, 75, 120, 60))
        self.HORISONTAL_IN_BEAM_TEXT_IN.setAccessibleName("")
        self.HORISONTAL_IN_BEAM_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setObjectName("HORISONTAL_IN_BEAM_TEXT_IN")
        self.HORISONTAL_DELTA_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_DELTA_TEXT_IN.setEnabled(True)
        self.HORISONTAL_DELTA_TEXT_IN.setGeometry(QtCore.QRect(110, 155, 120, 60))
        self.HORISONTAL_DELTA_TEXT_IN.setAccessibleName("")
        self.HORISONTAL_DELTA_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.HORISONTAL_DELTA_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.HORISONTAL_DELTA_TEXT_IN.setObjectName("HORISONTAL_DELTA_TEXT_IN")
        self.HORISONTAL_HOME_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_HOME_TEXT_IN.setEnabled(True)
        self.HORISONTAL_HOME_TEXT_IN.setGeometry(QtCore.QRect(110, 235, 120, 60))
        self.HORISONTAL_HOME_TEXT_IN.setAccessibleName("")
        self.HORISONTAL_HOME_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhSensitiveData)
        self.HORISONTAL_HOME_TEXT_IN.setAlignment(QtCore.Qt.AlignCenter)
        self.HORISONTAL_HOME_TEXT_IN.setObjectName("HORISONTAL_HOME_TEXT_IN")
        self.IN_BEAM_TEXT_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.IN_BEAM_TEXT_3.setEnabled(True)
        self.IN_BEAM_TEXT_3.setGeometry(QtCore.QRect(20, 85, 129, 34))
        self.IN_BEAM_TEXT_3.setObjectName("IN_BEAM_TEXT_3")
        self.DELTA_POS_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.DELTA_POS_3.setEnabled(True)
        self.DELTA_POS_3.setGeometry(QtCore.QRect(20, 165, 151, 34))
        self.DELTA_POS_3.setObjectName("DELTA_POS_3")
        self.HOME_TEXT_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.HOME_TEXT_3.setEnabled(True)
        self.HOME_TEXT_3.setGeometry(QtCore.QRect(20, 248, 129, 34))
        self.HOME_TEXT_3.setObjectName("HOME_TEXT_3")
        self.MOVE_X_HOME = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.MOVE_X_HOME.setGeometry(QtCore.QRect(330, 235, 141, 60))
        self.MOVE_X_HOME.setObjectName("MOVE_X_HOME")
        self.MOVE_X_INBEAM = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.MOVE_X_INBEAM.setGeometry(QtCore.QRect(330, 75, 141, 60))
        self.MOVE_X_INBEAM.setObjectName("MOVE_X_INBEAM")
        self.MOVE_X_OUTBEAM = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.MOVE_X_OUTBEAM.setGeometry(QtCore.QRect(330, 155, 141, 60))
        self.MOVE_X_OUTBEAM.setObjectName("MOVE_X_OUTBEAM")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 490, 1045, 261))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(980, 40, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 40, 171, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JEPO TARGET CONTROL"))
        self.on_off_BTN.setText(_translate("MainWindow", "OFF"))
        self.GROUP_VERTICAL.setTitle(_translate("MainWindow", "VERTICAL"))
        self.VERTICAL_HOME_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.VERTICAL_DELTA_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.VERTICAL_IN_BEAM_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.IN_BEAM_TEXT.setText(_translate("MainWindow", "IN BEAM"))
        self.DELTA_POS.setText(_translate("MainWindow", "DELTA POS"))
        self.HOME_TEXT.setText(_translate("MainWindow", "HOME"))
        self.MOVE_Y_INBEAM.setText(_translate("MainWindow", "Move Y IN Beam"))
        self.MOVE_Y_OUTBEAM.setText(_translate("MainWindow", "Move Y Out Beam"))
        self.MOVE_Y_HOME.setText(_translate("MainWindow", "Move Y In Home"))
        self.auto_manual_checkbox.setText(_translate("MainWindow", "MANUAL"))
        self.GROUP_HORISONTAL.setTitle(_translate("MainWindow", "HORISONTAL"))
        self.HORISONTAL_HOME_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.HORISONTAL_DELTA_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.HORISONTAL_IN_BEAM_SET_BUTTON.setText(_translate("MainWindow", "SET"))
        self.IN_BEAM_TEXT_3.setText(_translate("MainWindow", "IN BEAM"))
        self.DELTA_POS_3.setText(_translate("MainWindow", "DELTA POS"))
        self.HOME_TEXT_3.setText(_translate("MainWindow", "HOME"))
        self.MOVE_X_HOME.setText(_translate("MainWindow", "Move X In Home"))
        self.MOVE_X_INBEAM.setText(_translate("MainWindow", "Move X IN Beam"))
        self.MOVE_X_OUTBEAM.setText(_translate("MainWindow", "Move X Out Beam"))
        self.comboBox.setItemText(0, _translate("MainWindow", "File"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EPICS"))
        self.label.setText(_translate("MainWindow", "Load configuration from:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
