# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JEPO_TARGET_CONTROL.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 813)
        MainWindow.setMouseTracking(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.on_off_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.on_off_BTN.setGeometry(QtCore.QRect(40, 30, 120, 48))
        self.on_off_BTN.setAutoDefault(False)
        self.on_off_BTN.setDefault(False)
        self.on_off_BTN.setFlat(False)
        self.on_off_BTN.setObjectName("on_off_BTN")
        self.GROUP_VERTICAL = QtWidgets.QGroupBox(self.centralwidget)
        self.GROUP_VERTICAL.setEnabled(True)
        self.GROUP_VERTICAL.setGeometry(QtCore.QRect(40, 130, 485, 331))
        self.GROUP_VERTICAL.setAutoFillBackground(False)
        self.GROUP_VERTICAL.setInputMethodHints(QtCore.Qt.ImhNone)
        self.GROUP_VERTICAL.setFlat(True)
        self.GROUP_VERTICAL.setCheckable(False)
        self.GROUP_VERTICAL.setObjectName("GROUP_VERTICAL")
        self.VERTICAL_HOME_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_BUTTON.setEnabled(True)
        self.VERTICAL_HOME_BUTTON.setGeometry(QtCore.QRect(300, 235, 170, 60))
        self.VERTICAL_HOME_BUTTON.setObjectName("VERTICAL_HOME_BUTTON")
        self.VERTICAL_DELTA_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_BUTTON.setEnabled(True)
        self.VERTICAL_DELTA_BUTTON.setGeometry(QtCore.QRect(300, 155, 170, 60))
        self.VERTICAL_DELTA_BUTTON.setObjectName("VERTICAL_DELTA_BUTTON")
        self.VERTICAL_IN_BEAM_BUTTON = QtWidgets.QPushButton(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_BUTTON.setEnabled(True)
        self.VERTICAL_IN_BEAM_BUTTON.setGeometry(QtCore.QRect(299, 75, 170, 60))
        self.VERTICAL_IN_BEAM_BUTTON.setObjectName("VERTICAL_IN_BEAM_BUTTON")
        self.VERTICAL_IN_BEAM_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_IN_BEAM_TEXT_IN.setEnabled(True)
        self.VERTICAL_IN_BEAM_TEXT_IN.setGeometry(QtCore.QRect(167, 75, 120, 60))
        self.VERTICAL_IN_BEAM_TEXT_IN.setAutoFillBackground(False)
        self.VERTICAL_IN_BEAM_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.VERTICAL_IN_BEAM_TEXT_IN.setObjectName("VERTICAL_IN_BEAM_TEXT_IN")
        self.VERTICAL_DELTA_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_DELTA_TEXT_IN.setEnabled(True)
        self.VERTICAL_DELTA_TEXT_IN.setGeometry(QtCore.QRect(167, 155, 120, 60))
        self.VERTICAL_DELTA_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.VERTICAL_DELTA_TEXT_IN.setObjectName("VERTICAL_DELTA_TEXT_IN")
        self.VERTICAL_HOME_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_VERTICAL)
        self.VERTICAL_HOME_TEXT_IN.setEnabled(True)
        self.VERTICAL_HOME_TEXT_IN.setGeometry(QtCore.QRect(167, 235, 120, 60))
        self.VERTICAL_HOME_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.VERTICAL_HOME_TEXT_IN.setObjectName("VERTICAL_HOME_TEXT_IN")
        self.IN_BEAM_TEXT = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.IN_BEAM_TEXT.setEnabled(True)
        self.IN_BEAM_TEXT.setGeometry(QtCore.QRect(10, 85, 129, 34))
        self.IN_BEAM_TEXT.setObjectName("IN_BEAM_TEXT")
        self.DELTA_POS = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.DELTA_POS.setEnabled(True)
        self.DELTA_POS.setGeometry(QtCore.QRect(10, 165, 151, 34))
        self.DELTA_POS.setObjectName("DELTA_POS")
        self.HOME_TEXT = QtWidgets.QLabel(self.GROUP_VERTICAL)
        self.HOME_TEXT.setEnabled(True)
        self.HOME_TEXT.setGeometry(QtCore.QRect(10, 248, 129, 34))
        self.HOME_TEXT.setObjectName("HOME_TEXT")
        self.auto_manual_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_manual_checkbox.setGeometry(QtCore.QRect(180, 33, 175, 40))
        self.auto_manual_checkbox.setObjectName("auto_manual_checkbox")
        self.GROUP_HORISONTAL = QtWidgets.QGroupBox(self.centralwidget)
        self.GROUP_HORISONTAL.setEnabled(True)
        self.GROUP_HORISONTAL.setGeometry(QtCore.QRect(600, 130, 485, 331))
        self.GROUP_HORISONTAL.setAutoFillBackground(False)
        self.GROUP_HORISONTAL.setFlat(True)
        self.GROUP_HORISONTAL.setCheckable(False)
        self.GROUP_HORISONTAL.setObjectName("GROUP_HORISONTAL")
        self.HORISONTAL_HOME_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_HOME_BUTTON.setEnabled(True)
        self.HORISONTAL_HOME_BUTTON.setGeometry(QtCore.QRect(300, 235, 170, 60))
        self.HORISONTAL_HOME_BUTTON.setObjectName("HORISONTAL_HOME_BUTTON")
        self.HORISONTAL_DELTA_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_DELTA_BUTTON.setEnabled(True)
        self.HORISONTAL_DELTA_BUTTON.setGeometry(QtCore.QRect(300, 155, 170, 60))
        self.HORISONTAL_DELTA_BUTTON.setObjectName("HORISONTAL_DELTA_BUTTON")
        self.HORISONTAL_IN_BEAM_BUTTON = QtWidgets.QPushButton(self.GROUP_HORISONTAL)
        self.HORISONTAL_IN_BEAM_BUTTON.setEnabled(True)
        self.HORISONTAL_IN_BEAM_BUTTON.setGeometry(QtCore.QRect(299, 75, 170, 60))
        self.HORISONTAL_IN_BEAM_BUTTON.setObjectName("HORISONTAL_IN_BEAM_BUTTON")
        self.HORISONTAL_IN_BEAM_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setEnabled(True)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setGeometry(QtCore.QRect(167, 75, 120, 60))
        self.HORISONTAL_IN_BEAM_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.HORISONTAL_IN_BEAM_TEXT_IN.setObjectName("HORISONTAL_IN_BEAM_TEXT_IN")
        self.HORISONTAL_DELTA_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_DELTA_TEXT_IN.setEnabled(True)
        self.HORISONTAL_DELTA_TEXT_IN.setGeometry(QtCore.QRect(167, 155, 120, 60))
        self.HORISONTAL_DELTA_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.HORISONTAL_DELTA_TEXT_IN.setObjectName("HORISONTAL_DELTA_TEXT_IN")
        self.HORISONTAL_HOME_TEXT_IN = QtWidgets.QLineEdit(self.GROUP_HORISONTAL)
        self.HORISONTAL_HOME_TEXT_IN.setEnabled(True)
        self.HORISONTAL_HOME_TEXT_IN.setGeometry(QtCore.QRect(167, 235, 120, 60))
        self.HORISONTAL_HOME_TEXT_IN.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.HORISONTAL_HOME_TEXT_IN.setObjectName("HORISONTAL_HOME_TEXT_IN")
        self.IN_BEAM_TEXT_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.IN_BEAM_TEXT_3.setEnabled(True)
        self.IN_BEAM_TEXT_3.setGeometry(QtCore.QRect(10, 85, 129, 34))
        self.IN_BEAM_TEXT_3.setObjectName("IN_BEAM_TEXT_3")
        self.DELTA_POS_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.DELTA_POS_3.setEnabled(True)
        self.DELTA_POS_3.setGeometry(QtCore.QRect(10, 165, 151, 34))
        self.DELTA_POS_3.setObjectName("DELTA_POS_3")
        self.HOME_TEXT_3 = QtWidgets.QLabel(self.GROUP_HORISONTAL)
        self.HOME_TEXT_3.setEnabled(True)
        self.HOME_TEXT_3.setGeometry(QtCore.QRect(10, 248, 129, 34))
        self.HOME_TEXT_3.setObjectName("HOME_TEXT_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 490, 1045, 261))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setLineWidth(2)
        self.textBrowser.setMidLineWidth(0)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JEPO TARGET CONTROL"))
        self.on_off_BTN.setText(_translate("MainWindow", "OFF"))
        self.GROUP_VERTICAL.setTitle(_translate("MainWindow", "VERTICAL"))
        self.VERTICAL_HOME_BUTTON.setText(_translate("MainWindow", "HOME"))
        self.VERTICAL_DELTA_BUTTON.setText(_translate("MainWindow", "DELTA POS"))
        self.VERTICAL_IN_BEAM_BUTTON.setText(_translate("MainWindow", "IN BEAM"))
        self.IN_BEAM_TEXT.setText(_translate("MainWindow", "IN BEAM"))
        self.DELTA_POS.setText(_translate("MainWindow", "DELTA POS"))
        self.HOME_TEXT.setText(_translate("MainWindow", "HOME"))
        self.auto_manual_checkbox.setText(_translate("MainWindow", "MANUAL"))
        self.GROUP_HORISONTAL.setTitle(_translate("MainWindow", "HORISONTAL"))
        self.HORISONTAL_HOME_BUTTON.setText(_translate("MainWindow", "HOME"))
        self.HORISONTAL_DELTA_BUTTON.setText(_translate("MainWindow", "DELTA POS"))
        self.HORISONTAL_IN_BEAM_BUTTON.setText(_translate("MainWindow", "IN BEAM"))
        self.IN_BEAM_TEXT_3.setText(_translate("MainWindow", "IN BEAM"))
        self.DELTA_POS_3.setText(_translate("MainWindow", "DELTA POS"))
        self.HOME_TEXT_3.setText(_translate("MainWindow", "HOME"))


